'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import arcane from '../../../../public/images/arcane/Mask group.webp';
import book from '../../../../public/images/book/Book.webp';
import CancelBTN from '../../../../public/images/cancelBtn.png';
import crow from '../../../../public/images/crow/Mask group.webp';
import DontFound from '../../../../public/images/no_cards_found/noCardsFound.webp';
import GridContainer from '../Carousel/GridContainer';
import MobileCorusel from '../Carousel/MobileCorusel';
import Filters from '../Filters/Filters';

const mana = ['Mana: low to high', 'Mana: high to low'];

const card = {
  cardid: 'EX1_271',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card2 = {
  cardid: 'EX1_272',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card3 = {
  cardid: 'EX1_273',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card4 = {
  cardid: 'EX1_274',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card5 = {
  cardid: 'EX1_275',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card6 = {
  cardid: 'EX1_276',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card7 = {
  cardid: 'EX1_277',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card8 = {
  cardid: 'EX1_278',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card9 = {
  cardid: 'EX1_279',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card10 = {
  cardid: 'EX1_280',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: arcane,
};
const card11 = {
  cardid: 'EX1_281',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card12 = {
  cardid: 'EX1_282',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card13 = {
  cardid: 'EX1_283',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card14 = {
  cardid: 'EX1_284',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card15 = {
  cardid: 'EX1_285',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card16 = {
  cardid: 'EX1_286',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card17 = {
  cardid: 'EX1_287',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card18 = {
  cardid: 'EX1_288',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};
const card19 = {
  cardid: 'EX1_289',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: crow,
};
const card20 = {
  cardid: 'EX1_290',
  cardname: 'Arcane Missiles',
  cardset: 'Classic',
  type: 'Spell',
  rarity: 'Common',
  attack: 0,
  health: 0,
  text: 'Deal $3 damage randomly split among all enemies.',
  race: 'Undead',
  playerclass: 'Mage',
  img: book,
};

const cards = [
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card11,
  card12,
  card13,
  card14,
  card15,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,

  card20,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card11,
  card12,
  card13,
  card14,
  card15,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,

  card20,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card11,
  card12,
  card13,
  card14,
  card15,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card16,
  card17,
  card18,
  card19,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card16,
  card17,
  card18,
  card19,
  card20,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card,
  card2,
  card3,
  card4,
  card5,
  card6,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
  card14,
  card15,
  card20,
];

type SearchProps = {
  search: string;
  cancelBtn: () => void;
};
export default function FilterResult({ search, cancelBtn }: SearchProps) {
  const [filtersActive, setFilterActive] = useState(false);
  const [results, setResults] = useState('null');
  const showFilters = () => {
    setFilterActive(!filtersActive);
  };

  const [activeFilters, setActiveFilters] = useState(false);
  const [activeDropdown, setActiveDropdown] = useState(false);

  const openDropdown = () => {
    setActiveDropdown(!activeDropdown);
  };

  const openFilters = () => {
    setActiveFilters(!activeFilters);
  };

  const [manaLabel, setManaLabel] = useState(mana[0]);

  useEffect(() => {
    setManaLabel(manaLabel);
  }, []);

  const content = (
    <>
      {results && (
        <>
          <div className="hidden md:block">
            <Filters
              manaLabel={manaLabel}
              atkLabel={'Attack'}
              healthLabel={'Health'}
              cardTypeLabel={'Card Type'}
              minionTypeLabel={'Minion Type'}
              rarityLabel={'Rarity'}
              keywordsLabel={'Keyword'}
              activeFiltersBTN={function (active: boolean): void {
                console.log(active);
              }}
            ></Filters>
          </div>
        </>
      )}
      <div className="md:hidden flex w-full ml-9">
        <button
          className="text-gold font-AclonicaR text-xl flex"
          onClick={cancelBtn}
        >
          CANCEL SEARCH
          <Image className="mx-6" src={CancelBTN} alt={''} />
        </button>
      </div>
      <div className="mt-5 md:mt-12 flex items-center w-full md:mb-12">
        <p className="font-AclonicaR text-white text-2xl ml-6 md:text-5xl md:ml-32">
          {!results && '0'} Results for: &quot;{search}&quot;
        </p>
        <Image
          className="hidden mx-6 md:flex"
          src={CancelBTN}
          alt={''}
          onClick={cancelBtn}
        />
      </div>
      <Filters
        manaLabel={manaLabel}
        atkLabel={'Attack'}
        healthLabel={'Health'}
        cardTypeLabel={'Card Type'}
        minionTypeLabel={'Minion Type'}
        rarityLabel={'Rarity'}
        keywordsLabel={'Keyword'}
        activeFiltersBTN={function (active: boolean): void {
          console.log(active);
        }}
      ></Filters>
      {results ? (
        <>
          <div className="hidden md:block w-full px-8 overflow-x-hidden">
            <GridContainer cards={cards ? cards : []}></GridContainer>
          </div>
          <div className="md:hidden w-full px-8 overflow-x-hidden items-center h-full">
            <MobileCorusel cardList={cards} />
          </div>
        </>
      ) : (
        <>
          <div className="flex flex-col justify-center items-center mt-10">
            <Image className="" src={DontFound} alt={''} onClick={cancelBtn} />
            <p className="text-white font-AclonicaR text-3xl mt-11">
              Blasphemy! No cards found.
            </p>
            <p
              className="font-AclonicaR text-gold underline cursor-pointer"
              onClick={cancelBtn}
            >
              Your quest isn’t over! Try a new search.
            </p>
          </div>
        </>
      )}
    </>
  );
  return content;
}
